// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnjgsbpnrmpozhokylhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuamdzYnBucm1wb3pob2t5bGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzU1NDYsImV4cCI6MjA3MDI1MTU0Nn0.gZzEDLmCoyzcau3To79ON-sdweIGwtzFvRryCOChMb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});